input_beam:
  style: distgen
  distgen_input_file: input/dipole_chirp500_beam.yaml

input_lattice:
  lattice_input_file: input/dipole_lattice_fine.yaml

particle_deposition:
  xbins: 100
  zbins: 100
  xlim: 5
  zlim: 5
  filter_order: 2
  filter_window: 5
  velocity_threhold: 1000

CSR_integration:
  n_formation_length: 1.5
  zbins: 100
  xbins: 100

CSR_computation:
  compute_CSR: 1
  apply_CSR: 1
  transverse_on: 1
  xbins: 10
  zbins: 30
  xlim: 3
  zlim: 3
  write_beam: [1]
  write_wakes: True
  write_name: 'dipole_chirp500_fine'
  workdir: './output'
