import numpy as np
import sys
from distgen import Generator
def generate_beams(input_beam):
    """
    generate initial beams from particle files or generated by distgen
    :param input_beam: dictionary containing beam info
    :return: Xs (npart, 6) numpy array. Columns are (x, xp, y ,yp, z, gamma)
    """
    if input_beam['style'] == 'from_file':
        filename = input_beam['beamfile']
        Xs = np.loadtxt(filename)

    elif input_beam['style'] == 'distgen':
        filename = input_beam['distgen_input_file']
        gen = Generator(filename)
        gen.run()
        pg = gen.particles
        Xs = np.vstack((pg.x, pg.xp, pg.y, pg.yp, pg.z, pg.gamma)).T



    else:
        sys.exit('Invalid input beam style')

    return Xs

